pipelines:
  branches:
    master:
      - step:
          image: oktupol/bitbucket-pipelines-php71
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - apt-get update && apt-get install -y git openssh-server
            - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
            - ./vendor/bin/phpunit --testsuite "Unit Test Suite"
      - step:
          image: node:10.15
          name: jest unit test
          caches:
            - node
          script:
            - mv .npmrc.example .npmrc
            - npm install
            - npm install jest -g
            - jest

definitions:
  caches:
    vendor-directory: vendor
